# Generated by Django 4.2.17 on 2024-12-19 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='photo_url',
        ),
    ]
